name: jkv
description: "A new Flutter project."
publish_to: 'none'  # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider:
  image_picker:
  firebase_core:
  firebase_auth:
  path_provider:
  http:
  firebase_storage:
  cupertino_icons: ^1.0.6
  cached_network_image: ^3.4.1
  lottie:
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.14.2"  # Keep this line, as it installs the launcher icon package
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/JKV-logo.png

flutter_icons:  # Corrected section for flutter_launcher_icons configuration
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/JKV-logo.png"
